name: Deploy WASM

on:
  workflow_call:

jobs:
  dotnet-deploy:
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        cache: true
        cache-dependency-path: ./Sources/packages.lock.json
        
    - run: dotnet restore --locked-mode --force-evaluate
          
    # slows down publish, but optimizes wasm
    # - run: dotnet workload install wasm-tools
  
    - name: Publish
      run: dotnet publish -c Release -o Public Sources/BlazorFirebaseTest.csproj --no-restore
      
    - name: Upload Public
      uses: actions/upload-artifact@v4
      with: 
        name: Public
        path: ./Public
        retention-days: 1